# Generated by Django 5.1.2 on 2024-10-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Montadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('foundation_year', models.IntegerField()),
            ],
            options={
                'ordering': ['name', 'foundation_year'],
            },
        ),
    ]
