# Generated by Django 5.1.2 on 2024-10-17 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montadoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Digite o nome...', max_length=200)),
                ('valor_referencia', models.IntegerField()),
                ('motorizacao', models.IntegerField()),
                ('turbo', models.BooleanField()),
                ('automatico', models.BooleanField()),
                ('montadora_id', models.ForeignKey(help_text='Selecione a montadora deste modelo', on_delete=django.db.models.deletion.CASCADE, to='montadoras.montadora')),
            ],
        ),
    ]
