# Generated by Django 5.1.2 on 2024-10-17 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montadoras', '0002_modeloveiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cor', models.CharField(max_length=150)),
                ('ano_fabricacao', models.IntegerField()),
                ('ano_modelo', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('placa', models.CharField(max_length=20)),
                ('vendido', models.BooleanField()),
                ('modelo_id', models.ForeignKey(help_text='Selecione o modelo deste veículo', on_delete=django.db.models.deletion.CASCADE, to='montadoras.modeloveiculo')),
            ],
        ),
    ]
