# Generated by Django 5.1.2 on 2024-10-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montadoras', '0003_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloveiculo',
            name='montadora_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montadoras.montadora'),
        ),
        migrations.AlterField(
            model_name='modeloveiculo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montadoras.modeloveiculo'),
        ),
    ]
