# Generated by Django 5.1.2 on 2024-10-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montadoras', '0004_alter_modeloveiculo_montadora_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='montadora',
            name='avatar_url',
            field=models.CharField(default='images/fiat-logo.png', max_length=200),
            preserve_default=False,
        ),
    ]
