# Generated by Django 5.1.3 on 2024-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montadoras', '0005_montadora_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloveiculo',
            name='motorizacao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='modeloveiculo',
            name='valor_referencia',
            field=models.FloatField(),
        ),
    ]
